// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Execa from "execa";
import * as Rollup from "rollup";
import * as Nodefs from "node:fs";
import * as Nodepath from "node:path";
import * as Stdlib_JSON from "rescript/lib/es6/Stdlib_JSON.js";
import * as Stdlib_List from "rescript/lib/es6/Stdlib_List.js";
import * as Stdlib_Option from "rescript/lib/es6/Stdlib_Option.js";
import * as PluginNodeResolve from "@rollup/plugin-node-resolve";

let projectPath = "./";

let artifactsPath = Nodepath.join(projectPath, "./artifacts");

let sourePaths = [
  "package.json",
  "src",
  "rescript.json",
  "README.md",
  "jsr.json"
];

function update(json, path, value) {
  let dict = Stdlib_JSON.Decode.object(json);
  let dict$1 = dict !== undefined ? Object.assign({}, dict) : ({});
  if (path === 0) {
    return value;
  }
  let path$1 = path.tl;
  let key = path.hd;
  if (path$1 !== 0) {
    dict$1[key] = update(Stdlib_Option.getOr(dict$1[key], {}), path$1, value);
    return dict$1;
  } else {
    dict$1[key] = value;
    return dict$1;
  }
}

if (Nodefs.existsSync(artifactsPath)) {
  Fs.rmSync(artifactsPath, {
    recursive: true,
    force: true
  });
}

Nodefs.mkdirSync(artifactsPath);

Nodefs.mkdirSync(Nodepath.join(artifactsPath, "tests"));

Nodefs.mkdirSync(Nodepath.join(artifactsPath, "scripts"));

let filesMapping = [
  [
    "Error",
    "S.$$Error.$$class"
  ],
  [
    "string",
    "S.string"
  ],
  [
    "boolean",
    "S.bool"
  ],
  [
    "int32",
    "S.int"
  ],
  [
    "number",
    "S.float"
  ],
  [
    "bigint",
    "S.bigint"
  ],
  [
    "symbol",
    "S.symbol"
  ],
  [
    "never",
    "S.never"
  ],
  [
    "unknown",
    "S.unknown"
  ],
  [
    "any",
    "S.unknown"
  ],
  [
    "optional",
    "S.js_optional"
  ],
  [
    "nullable",
    "S.js_nullable"
  ],
  [
    "nullish",
    "S.nullable"
  ],
  [
    "array",
    "S.array"
  ],
  [
    "instance",
    "S.instance"
  ],
  [
    "unnest",
    "S.unnest"
  ],
  [
    "record",
    "S.dict"
  ],
  [
    "json",
    "S.json"
  ],
  [
    "enableJson",
    "S.enableJson"
  ],
  [
    "jsonString",
    "S.jsonString"
  ],
  [
    "enableJsonString",
    "S.enableJsonString"
  ],
  [
    "jsonStringWithSpace",
    "S.jsonStringWithSpace"
  ],
  [
    "uint8Array",
    "S.uint8Array"
  ],
  [
    "enableUint8Array",
    "S.enableUint8Array"
  ],
  [
    "union",
    "S.js_union"
  ],
  [
    "object",
    "S.object"
  ],
  [
    "schema",
    "S.js_schema"
  ],
  [
    "safe",
    "S.js_safe"
  ],
  [
    "safeAsync",
    "S.js_safeAsync"
  ],
  [
    "reverse",
    "S.reverse"
  ],
  [
    "parser",
    "S.parser"
  ],
  [
    "asyncParser",
    "S.asyncParser"
  ],
  [
    "decoder",
    "S.getDecoder"
  ],
  [
    "asyncDecoder",
    "S.asyncDecoder"
  ],
  [
    "encoder",
    "S.encoder"
  ],
  [
    "asyncEncoder",
    "S.asyncEncoder"
  ],
  [
    "assert",
    "S.js_assert"
  ],
  [
    "recursive",
    "S.recursive"
  ],
  [
    "merge",
    "S.js_merge"
  ],
  [
    "strict",
    "S.strict"
  ],
  [
    "deepStrict",
    "S.deepStrict"
  ],
  [
    "strip",
    "S.strip"
  ],
  [
    "deepStrip",
    "S.deepStrip"
  ],
  [
    "to",
    "S.js_to"
  ],
  [
    "toJSONSchema",
    "S.toJSONSchema"
  ],
  [
    "fromJSONSchema",
    "S.fromJSONSchema"
  ],
  [
    "extendJSONSchema",
    "S.extendJSONSchema"
  ],
  [
    "shape",
    "S.shape"
  ],
  [
    "tuple",
    "S.tuple"
  ],
  [
    "asyncParserRefine",
    "S.js_asyncParserRefine"
  ],
  [
    "refine",
    "S.js_refine"
  ],
  [
    "meta",
    "S.meta"
  ],
  [
    "toExpression",
    "S.toExpression"
  ],
  [
    "noValidation",
    "S.noValidation"
  ],
  [
    "compile",
    "S.compile"
  ],
  [
    "port",
    "S.port"
  ],
  [
    "min",
    "S.min"
  ],
  [
    "max",
    "S.max"
  ],
  [
    "length",
    "S.length"
  ],
  [
    "email",
    "S.email"
  ],
  [
    "uuid",
    "S.uuid"
  ],
  [
    "cuid",
    "S.cuid"
  ],
  [
    "url",
    "S.url"
  ],
  [
    "pattern",
    "S.pattern"
  ],
  [
    "datetime",
    "S.datetime"
  ],
  [
    "trim",
    "S.trim"
  ],
  [
    "global",
    "S.global"
  ],
  [
    "brand",
    "S.brand"
  ]
];

sourePaths.forEach(path => {
  Fs.cpSync(Nodepath.join(projectPath, path), Nodepath.join(artifactsPath, path), {
    recursive: true
  });
});

function writeSjsEsm(path) {
  Nodefs.writeFileSync(path, Buffer.from([
    "/* @ts-self-types=\"./S.d.ts\" */",
    "import * as S from \"./Sury.res.mjs\"",
    "export { unit as void } from \"./Sury.res.mjs\""
  ].concat(filesMapping.map(param => "export var " + param[0] + " = " + param[1])).join("\n")), {
    encoding: "utf8"
  });
}

writeSjsEsm(Nodepath.join(projectPath, "./src/S.js"));

writeSjsEsm(Nodepath.join(artifactsPath, "./src/S.mjs"));

Nodefs.writeFileSync(Nodepath.join(artifactsPath, "./src/S.js"), Buffer.from([
  "/* @ts-self-types=\"./S.d.ts\" */",
  "var S = require(\"./Sury.res.js\");"
].concat(filesMapping.map(param => "exports." + param[0] + " = " + param[1])).concat(["exports.void = S.unit"]).join("\n")), {
  encoding: "utf8"
});

function updateJsonFile(src, path, value) {
  let packageJsonData = Nodefs.readFileSync(src, {
    encoding: "utf8"
  });
  let packageJson = JSON.parse(packageJsonData.toString());
  let updatedPackageJson = JSON.stringify(update(packageJson, Stdlib_List.fromArray(path), value), undefined, 2);
  Nodefs.writeFileSync(src, Buffer.from(updatedPackageJson), {
    encoding: "utf8"
  });
}

Execa.execaSync("pnpm", ["rescript"], {
  cwd: artifactsPath
});

async function resolveRescriptRuntime(format, input, output) {
  let bundle = await Rollup.rollup({
    input: Nodepath.join(artifactsPath, input),
    plugins: [PluginNodeResolve.nodeResolve()]
  });
  await bundle.write({
    file: Nodepath.join(artifactsPath, output),
    format: format,
    exports: "named"
  });
  return await bundle.close();
}

await resolveRescriptRuntime("es", "src/Sury.res.mjs", "src/Sury.res.mjs");

await resolveRescriptRuntime("cjs", "src/Sury.res.mjs", "src/Sury.res.js");

await resolveRescriptRuntime("cjs", "src/S.res.mjs", "src/S.res.js");

updateJsonFile(Nodepath.join(artifactsPath, "package.json"), ["type"], "commonjs");

updateJsonFile(Nodepath.join(artifactsPath, "package.json"), ["private"], false);

Fs.rmSync(Nodepath.join(artifactsPath, "lib"), {
  recursive: true,
  force: true
});

Fs.rmSync(Nodepath.join(artifactsPath, "node_modules"), {
  recursive: true,
  force: true
});

/* artifactsPath Not a pure module */
